---
bg: Български
ca: Català
cs: Čeština
da: Dansk
de: Deutsch
el: Ελληνικά
en: English
es: Español
et: Eesti
eu: Basque
fi: Suomi
fr: Français
ga: Gaeilge
hr: Hrvatski
hu: Magyar
is: Íslenska
it: Italiano
lt: Lietuvių
lv: Latviešu
mt: Malti
nl: Nederlands
no: Norsk
pl: Polski
pt: Português
ro: Română
ru: Русский
sk: Slovenčina
sl: Slovenščina
sr: српски
sv: Svenska
uk: Українська
